#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: selenium-download-data-claim
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100M