image:
  repository: tccr.io/truecharts/jupyter-base
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:a51e8eb8a3c1452ed9a7342b82fdea233bf5b8f62d50fb8df71eb4ad06bae0fc
minimalImage:
  repository: tccr.io/truecharts/jupyter-minimal
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:b770ea9014a2ca9675149c8a00264613b78edfc198afafeb2aec230ec4c36705
rImage:
  repository: tccr.io/truecharts/jupyter-r
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:58dfdd4c0bb8655b53daf36af856c790e7512e990c5dace8722bae7f6a3a8b98
scipyImage:
  repository: tccr.io/truecharts/jupyter-scipy
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:c48b330e40906a5d58e69bec049f0d5711211da2345ea329010fee690cc5e2fb
tensorflowImage:
  repository: tccr.io/truecharts/jupyter-tensorflow
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:c9dc6a57ff9e8056b161dc99f21222c13540a46464724b0f6bef1f2ca1d22adf
datascienceImage:
  repository: tccr.io/truecharts/jupyter-datascience
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:f05bafd98deb0c2b7a2b69c31f27e969ae9caf9a4f0d46326d6e91f7e6f1add7
pysparkImage:
  repository: tccr.io/truecharts/jupyter-pyspark
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:975118d0e8b1812c9fd8a777277a12b305b6d69522cb58a4fcb00ec9776a81d2
allsparkImage:
  repository: tccr.io/truecharts/jupyter-all-spark
  pullPolicy: IfNotPresent
  tag: v2023-08@sha256:c79f699d34577ed5600355521f3d5de2f20d7964463f0fdd17cf38276f36ce59
jupyter:
  jupyter_cmd: lab
  restartable: true
service:
  main:
    ports:
      main:
        port: 10300
        protocol: http
        targetPort: 8888
persistence:
  data:
    enabled: true
    mountPath: /home/jovyan/work
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NB_UID: "{{ .Values.securityContext.container.PUID }}"
            NB_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            NB_UMASK: "{{ .Values.securityContext.container.UMASK }}"
            # User Defined
            DOCKER_STACKS_JUPYTER_CMD: "{{ .Values.jupyter.jupyter_cmd }}"
            RESTARTABLE: '{{ ternary "yes" "no" .Values.jupyter.restartable }}'

