apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradex-marketdatafullname" . }}
  labels:
    {{- include "tradex-marketdatalabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tradex-marketdataselectorLabels" . | nindent 4 }}
